# Generated by Django 5.2 on 2025-04-18 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Fund Name"
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(max_length=128, verbose_name="Fund Manager Name"),
                ),
                (
                    "description",
                    models.TextField(max_length=512, verbose_name="Fund Description"),
                ),
                (
                    "net_asset_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="NAV",
                        max_digits=14,
                        verbose_name="Fund Net Asset Value",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(verbose_name="Fund Date of Creation"),
                ),
                (
                    "performance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="As a percentage",
                        max_digits=8,
                        verbose_name="Fund Performance",
                    ),
                ),
            ],
        ),
    ]
